#!/usr/bin/env zsh
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh
pushd $DOTFILES/dotfiles
echo $STOW_FOLDERS
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -d "$HOME/.dotfiles/dotfiles" -t "$HOME" -D $folder
    stow -d "$HOME/.dotfiles/dotfiles" -t "$HOME" --target=$HOME $folder
done
popd
