# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

[colors.primary]
foreground = "#e0def4"
background = "#191724"

# [colors.selection]
# text = "#e0def4"
# background = "#403d52"

[colors.normal]
black = "#2e3436"
red = "#cc0000"
green = "#4e9a06"
yellow = "#c4a000"
blue = "#3465a4"
magenta = "#75507b"
cyan = "#06989a"
white = "#ffffff"

[colors.bright]
black = "#555753"
red = "#ef2929"
green = "#8ae234"
yellow = "#fce9f4"
blue = "#729fcf"
magenta = "#ad7fa8"
cyan = "#34e2e2"
white = "#d3d7cf"
